var messages = [
  "Você é a luz dos meus dias mais sombrios. 💡",
  "O amor é uma aventura, e eu escolhi você para ser minha companheira nessa jornada. 🧑🏻‍🤝‍👩🏽",
  "Seu sorriso é a minha maior motivação. 😄",
  "Você é mais doce do que o chocolate mais delicioso. 🍫",
  "Se eu pudesse reescrever o alfabeto inglês, colocaria 'U' e 'I' (You and I - Você e eu) juntos. 🧑🏻‍🤝‍👩🏽",
  "Seu amor é a melhor coisa que já me aconteceu. 🥰💘",
  "Juntos, somos imparáveis. 🧑🏻‍🤝‍👩🏽❤️",
  "Você é a minha inspiração diária. 💃🏻📝",
  "Você é o meu refúgio seguro em um mundo caótico. 🗺️🏠🧑🏻‍🤝‍👩🏽👨🏻‍❤️‍💋‍👩🏽",
  "A cada batida do meu coração, eu sinto o seu amor. 💓",
  "Você transforma os momentos simples em memórias eternas. ♾️",
  "No labirinto da vida, você é minha bússola. 🧭",
  "Cada dia ao seu lado é uma página de um conto de fadas real. 🧚🏾‍♀️",
  "Nada parece impossível quando estou com você. 🤩🥇",
  "Seu abraço é o meu lugar favorito na Terra. 🫂",
  "Você é a musa dos meus sonhos e a realidade dos meus dias. 🛌🏻💗",
  "No palco da vida, você é o meu ato principal. 🎭",
  "Você é a resposta para todas as minhas perguntas do coração. ❓❤️u❤️",
  "Sua presença é como um abraço para a minha alma. 🫂",
  "O amor que sinto por você é o eco de todo o universo conspirando a nosso favor. 💗u💗",
  "Como um pintor diante de uma tela em branco, sua presença dá cor à minha vida. 🎨🖌️",
  "Nossas histórias se entrelaçam como fios de um tecido infinito de amor. 🎀♾️❤️",
  "Você é o verso que falta na minha poesia, o refrão que embala a minha melodia. 🥹",
  "Nosso amor é como uma estrela cadente, brilhante e fugaz, mas eternizado em cada desejo realizado. ❤️",
  "Em um mundo de incertezas, você é minha única certeza. ❤️u❤️♾️",
  "O amor que compartilhamos é a essência que dá sentido a tudo. ❤️",
  "Com você, até as segundas-feiras têm um toque de romance. 🍷💘",
  "Seu sorriso é a chave que abre todas as portas do meu coração. 🚪❤️",
  "No palco da vida, você é a minha atriz principal e o amor é o roteiro que escrevemos juntos. ❤️",
  "Você é a inspiração por trás das minhas melhores palavras e gestos. ❤️",
  "Meu amor por você é como o oceano, profundo, vasto e eterno. ❤️",
  "Você é o meu porto seguro em meio à tempestade. ❤️⛈️",
  "Como uma estrela guia no céu noturno, você ilumina o caminho da minha vida. 🌟",
  "Você é o verso que falta na minha poesia, o refrão que embala a minha melodia. 🎶",
  "Nosso amor é uma jornada que vale a pena ser vivida, com você ao meu lado. ❤️",
  "Você é o sol que aquece os dias frios da minha existência. ☀️",
  "O seu amor é a música que embala a dança da minha vida. 🕺🏻🪩💃🏾",
  "Você é a melhor parte de mim, o complemento perfeito para minha alma. ❤️",
  "Sua presença é como uma brisa suave em um dia de verão, refrescante e revigorante. 🍃",
  "O amor que sinto por você é a força que impulsiona todos os meus passos. 💪🏻🚶🏻‍♂️",
  "Em um mundo caótico, você é a minha paz interior. 🏳️💟",
  "Você é a razão pela qual a cada amanhecer o mundo parece mais bonito. 🌄",
  "Sua voz é a melodia que embala meus sonhos mais doces. 🗣️🍬",
  "Você é a estrela que ilumina as noites escuras da minha vida. 🌃🌟",
  "Você é minha flor, delicada, cheirosa, linda e que quero cuidar todos os dias. 🌹",
  "Você é o sonho que nunca desejo acordar. 🍩",
  "Sua presença é como um farol, guiando-me através das águas turbulentas da vida. 💡",
  "Você é o tesouro mais precioso que encontrei nesta jornada chamada vida. 🎁💖",
  "Meu amor por você é o fogo que aquece minha alma em noites frias. ❤️‍🔥",
  "Em um mundo de oito bilhões de pessoas, você é minha pessoa favorita. 🤩🥇",
  "Você é a obra-prima que a vida pintou no quadro da minha existência. 🎨🖌️",
  "Você é o sonho que se tornou realidade, o conto de fadas que eu sempre quis viver. 👸🏾🧚🏾‍♀️",
  "Nosso amor é o destino traçado pelas estrelas, escrito nas páginas do tempo. 🌠⏳",
  "Você é a inspiração por trás dos meus sorrisos mais sinceros e dos meus olhos mais brilhantes. 🤩",
  "Com você, cada dia é uma nova página de uma história de amor sem fim. 💞📝♾️",
  "Você é a pessoa que torna meus dias mais felizes e minhas noites mais aconchegantes. 🌞🌛",
  "Meu amor por você é como uma chama, ardente e constante, nunca desvanecendo. 🔥❤️‍🔥",
  "Seu amor é a luz que guia meus passos na escuridão. 🕯️",
  "Você é o verso que completa minha poesia, a nota que harmoniza minha melodia. 🎼",
  "Nosso amor é como uma canção, tocando suavemente em meu coração. 🎶❤️",
  "Com você, eu encontrei o verdadeiro significado da palavra 'feliz'. 🤗",
  "Eu adoraria ser o vento para poder soprar em seus ouvidos o quanto você é deslumbrante. 😸",
  "Você é a pessoa que ilumina os meus dias, até mesmo os dias nublados. 💡",
  "Eu não sou um especialista em geografia, mas acho que eu encontrei o meu lugar favorito no mundo (do seu lado...). 🎶🧑🏻‍🤝‍👩🏽👨🏻‍❤️‍💋‍👩🏽",
  "Eu não sou nenhum expert em astronomia, mas tenho certeza de que você é a estrela mais brilhante que eu já vi. 😎🌞",
  "Tanto lugar para ficar, e eu fui ficar logo na sua. E não me arrependo nem um pouco. 🤗❤️",
  "Você é tudo que eu preciso. É a fórmula exata que nos faz perfeitos. ❤️",
  "A felicidade é multiplicada quando dividida com alguém tão especial como você. ❤️",
  "Você é o Google da minha vida, tudo que eu procuro, encontro em você. 🔎❤️",
  "Seu sorriso é como o sol iluminando o meu dia. 😁☀️",
  "Se beleza fosse tempo, você seria a eternidade. ❤️",
  "Se você fosse uma música, seria a minha favorita. 🎶❤️",
  "Você é a combinação perfeita de doçura e elegância. ❤️u❤️",
  "Você é o motivo das minhas melhores noites de sono e dos meus mais belos sonhos. ❤️U❤️",
  "Seu corpo é como uma obra de arte, sempre descubro novos detalhes para admirar. 🤤❤️",
  "O universo conspira a nosso favor desde o dia em que nos encontramos. ❤️",
  "Seus olhos são como estrelas que guiam meu caminho na escuridão. ❤️",
  "Se o amor fosse um crime, eu me declararia culpado só para estar ao seu lado. ❤️",
  "Você é a musa que inspira os versos mais bonitos que já escrevi. ❤️",
  "Cada segundo ao seu lado é uma eternidade de felicidade. ❤️",
  "Seus abraços são como um refúgio seguro em meio ao caos do mundo. 🫂🤗",
  "Você é como um diamante raro: único, valioso e impossível de resistir. 😻💎",
  "Com você, cada dia é uma aventura cheia de surpresas maravilhosas. ❤️",
  "Seu amor é o presente mais precioso que já recebi. 💝",
  "Você é o milagre que eu tanto esperei. ❤️",
  "Cada detalhe em você é uma obra-prima esculpida pelo próprio amor. ❤️",
  "Seu amor é a música que toca suavemente em meu coração, embalando meus sonhos mais doces. 💘",
  "Você é como uma poesia sem fim, cada verso mais bonito que o anterior. 🤗❤️",
  "Sua presença transforma até os momentos mais simples em memórias preciosas. ❤️",
  "No palco da vida, você é a protagonista da minha história mais bonita. ❤️",
  "Com você, eu encontrei a verdadeira definição de felicidade. 🤗❤️",
  "Você é o arco-íris após a tempestade, trazendo luz e esperança para minha vida. 🌈",
  "Sua risada é como música para os meus ouvidos, sempre me fazendo sorrir. 😄",
  "Você é como uma estrela cadente, brilhante e fugaz, mas deixando um rastro de magia por onde passa. ❤️",
  "Com você, cada dia é uma nova página de uma maravilhosa história de amor sem fim. ❤️",
  "Seu amor é como um farol, guiando-me com segurança através das águas turbulentas da vida. ❤️",
  "Sua presença é como um abraço caloroso em um dia frio, me confortando e me acalmando. ❤️",
  "No jardim do meu coração, você é a mais bela flor, desabrochando em cores de amor. ❤️",
  "Seu amor é o oceano onde mergulho sem medo, pois sei que suas águas sempre me levarão de volta para casa. ❤️",
  "Nosso amor é como uma sinfonia celestial, onde cada nota é uma expressão do nosso amor eterno. ❤️",
  "Como uma pintura impressionista, nosso amor é uma mistura de cores vivas e suaves, criando uma obra-prima única e eterna. ❤️🎨",
  "Seus olhos são poemas silenciosos que ecoam os desejos mais profundos do meu coração. 🤗💘",
  "Em cada batida do meu coração, ecoa o nome da minha amada Ellaine, a melodia mais bonita que já conheci. 🎶💘",
  "Você é a estrela que guia meus passos na escuridão, a luz que ilumina meu caminho na noite mais escura. 🌃🌠",
  "Seu amor é como um livro aberto, onde descubro novos capítulos a cada dia, cada um mais emocionante que o anterior. 📖",
  "Nosso amor é como uma obra de arte, sempre revelando novos detalhes e significados a cada olhar. 💘",
  "Você é a poesia que habita os meus sonhos, a inspiração por trás dos meus versos mais bonitos. 💘",
  "Com você, cada momento é uma pintura impressionante, retratando a beleza e a profundidade do nosso amor. 💘🤗💝",
  "Seu sorriso é a inspiração dos meus mais felizes pensamentos. 💝",
  "Você é a musa dos meus sonhos, a inspiração por trás dos meus versos, a razão pela qual meu coração bate mais forte. 🤗💘",
  "Nosso amor é uma dança eterna, onde nossos corações são os únicos dançarinos, seguindo o ritmo da paixão e da felicidade. 🎶👯💘",
  "Seu sorriso é como o sol, iluminando meu mundo e aquecendo meu coração. 😸❤️‍🔥",
  "Ellaine, se beleza fosse crime, você estaria cumprindo prisão perpétua no meu coração. 😸🤗❤️",
  "Seu cabelo cacheado é como uma cascata de chocolate, irresistível e delicioso aos olhos. ❤️",
  "Ellaine, você é como um diamante raro, valiosa e única em cada detalhe. ❤️",
  "Você é como um raio de sol em um dia chuvoso, trazendo luz e calor para minha vida. 🤗❤️‍🔥",
  "Seu charme e elegância me deixam sem palavras, apenas admirando sua beleza sem igual. 🤤😻❤️",
  "Ellaine, se eu fosse um jardim, você seria a flor mais deslumbrante e radiante que nele floresce. ❤️",
  "Com você, cada momento é uma aventura emocionante, cheia de surpresas e risadas. 🤗😸❤️",
  "Se eu fosse um poeta, escreveria sonetos intermináveis para expressar a beleza do seu ser. ❤️",
  "Você é como um imã, atraindo minha atenção e meu coração com sua graça e carisma. 🤗❤️",
  "Ellaine, sua personalidade vibrante e divertida ilumina cada ambiente por onde passa. 😸❤️",
  "Sua força e determinação são inspiradoras, mostrando que você é capaz de superar qualquer desafio. 💪🏾👩🏾‍🎓🥇",
  "Com seu sorriso encantador e sua meiguice incomparável, você conquista a todos ao seu redor. 🧐❤️",
  "Ellaine, sua presença é como um abraço acolhedor, preenchendo meu coração com paz e alegria. 🤗❤️‍🔥",
  "Você é como um oásis no deserto, trazendo alívio e frescor para minha alma sedenta. 🤤❤️",
  "Sua inteligência e perspicácia são fascinantes, mostrando que você é muito mais do que apenas beleza exterior. ❤️",
  "Ellaine, sua doçura e ternura são como um bálsamo para minha alma, acalmando e confortando em momentos difíceis. 💘",
  "Com sua elegância natural e seu charme cativante, você é a personificação da graça e da beleza. 😻",
  "Seu jeito meigo e afetuoso torna cada momento ao seu lado uma experiência inesquecível e especial. 🤗❤️‍🔥",
  "Ellaine, sua determinação e coragem são admiráveis, mostrando que você enfrenta a vida com bravura e determinação. 💪🏾😻🥇",
  "Ellaine, morena de cabelos cacheados, és como uma deusa dos céus, iluminando meu mundo com teu brilho incomparável. 😸💘",
  "Seus olhos são como poços profundos de mistério, onde me perco e encontro o verdadeiro significado do amor. ❤️",
  "Com sua presença, Ellaine, cada momento se transforma em uma obra de arte, digna de ser apreciada por toda a eternidade. 💘",
  "Ellaine, em seu abraço encontro o conforto e a segurança que tanto busco, o refúgio perfeito em meio ao caos do mundo. 💘🤗",
  "Sua voz é como uma melodia suave, acalmando minha alma e embalando meus sonhos mais doces. 🎶😻",
  "Ellaine, em cada traço do seu ser encontro a perfeição de um universo criado para mim. ❤️‍🔥u❤️‍🔥",
  "Com sua presença suave e serena, Ellaine, você transforma o mundo ao seu redor em um lugar mais bonito e acolhedor. 😻🤗❤️‍🔥",
  "Ellaine, cada batida do meu coração é um eco do amor que sinto por você, um tributo à sua beleza e bondade sem igual. 🤗😻❤️‍🔥💘",
  "Seu amor é como uma chama eterna, ardente e brilhante, iluminando meu caminho e aquecendo minha alma. 🤗😻❤️‍🔥",
  "Ellaine, em cada sorriso seu encontro a razão para acreditar na felicidade e na beleza deste mundo. ❤️",
  "Ellaine, você é minha beldade. 🤗😻💘",
  "Ellaine, você é minha amada. 🤗❤️‍🔥u❤️‍🔥",
  "Ellaine, você é minha patroa. 👸🏾😼",
  "Ellaine, você é minha mandante. 😼👸🏾",
  "Ellaine, você é o amor da minha vida. 💘♾️",
  "Ellaine, você é a razão de todos os meus sorrisos fáceis e bobos. 😻😸❤️‍🔥",
  "Ellaine, você é a nutricionista da minha vida, deixando ela mais leve e saudável. 🪶💘",
  "Ellaine, nem todos os elogios do mundo parecem ser o suficiente para descrever a sua magnitude, o quão excepcional você é. 💘❤️‍🔥u❤️‍🔥",
  "Ellaine, você é muito mais do que eu sempre sonhei. 💝",
  "Ellaine, você é minha bonequinha. 🤗❤️",
  "Ellaine, você é minha princesa. 👸🏾💘",
  "Ellaine, sou muito grato por tê-la na minha vida. 🤗💝",
  "Ellaine, você é muito especial para mim. 🤗❤️‍🔥💝",
  "Ellaine, você é meu tudo de bom. 🤗😻💝❤️‍🔥❤️😸",
  "Ellaine, você é muito amada, nunca se esqueça. 😘🥰",
  "Ellaine, você me faz sentir o homem mais sortudo do mundo, muito obrigado por ser tão maravilhosa e me dar o privilégio de tê-la em minha vida. 🤞🏻💝",
  "Ellaine, você é com você que quero casar, construir família e viver a vida. ❤️",
  "Lhe amo muito mais do que sou capaz de descrever. 💘😍",
  "Não sou perfeito, mas por você eu tento, para - quem sabe um dia - chegar mais perto do seu patamar. 🥰🤞🏻💝🤗😻",
  "Você é oto patamar. 😸💝",
  "Nunca tive alguém como você na minha vida, você me faz sentir finalmente exaltado, após ser tão humilhado. 🤗🥰💝",
  "É você que me vem a mente quando penso em felicidade. 😍🤗😸😘",
  "Não quero lhe perder nunca, não sou perfeito, mesmo sendo impossível - por você eu tento ser - pois é o que você merece. 🥺💝🤞🏻",
  "Quero lhe proporcionar o melhor da vida, sentir-se amada e acolhida, além de poder desfrutar das coisas boas ao lado de quem lhe ama verdadeiramente. 🥰🤞🏻💝",
  "Do seu lado, sou tão forte... 🎵",
  "Eu amo muito você. ❤️u❤️",
  "Sabe que lhe amo muito, né? ❤️",
  "Nunca se esqueça que eu lhe amo muito. ❤️",
  "Nunca se esqueça: tem uma pessoa esperando por você (eu). ❤️",
  "Queria ser grego, mas grego não posso ser, porque grego tem vários deuses e minha única deusa é você. ❤️u❤️",
  "Você é sensacional. ❤️u❤️",
  "Você é minha pessoa favorita. ❤️",
  "Eu lhe amo verdadeiramente. 😍",
  "Quero cuidar de você para sempre. ❤️",
  "Quero lhe fazer mil e uma juras de amor e cumprir todas. 🤗💍",
  "Ellaine, em seu olhar vejo o reflexo do paraíso, onde o amor floresce em cores vibrantes e promessas eternas. 👀🤩",
  "Com você, Ellaine, cada momento se torna uma página de um conto de fadas, onde o amor é o protagonista e a felicidade é o desfecho garantido. 💘",
  "Seu amor, Ellaine, é a sinfonia que embala minha alma, uma melodia suave e envolvente que ressoa em cada fibra do meu ser. 🤗❤️",
  "Ellaine, como a lua em uma noite estrelada, você ilumina meu caminho e enche meu coração de encanto e admiração. 🌚",
  "Em cada traço do seu sorriso, Ellaine, encontro a promessa de dias ensolarados e noites estreladas, repletas de amor e alegria. 😸🌚🌞",
  "Seu sorriso, Ellaine, é como um poema em versos livres, fluindo suavemente e encantando todos ao seu redor. 😸💘",
  "Com você, Ellaine, descubro os segredos do universo e os mistérios do amor, em uma jornada eterna de descobertas e encantamentos. 💘u💘",
  "Ellaine, sua beleza transcende os limites da imaginação, como uma obra de arte divinamente esculpida pelos deuses do amor. 🤤❤️‍🔥",
  "Seu amor, Ellaine, é a luz que guia meus passos na escuridão, a âncora que me mantém seguro em meio às tempestades da vida. 💘",
  "Cada palavra sua é como um verso de poesia, que ecoa suavemente em minha mente e ressoa em meu coração, enchendo-me de amor e inspiração. ❤️",
  "Ellaine, em sua presença encontro a plenitude da minha existência, a razão pela qual cada respiração é uma celebração da vida e do amor. ❤️🎉",
  "Quem diria que um simples rolê aleatório traria tantas coisas boas (como o amor da minha vida), né? Bendito seja 03/02/2024. ❤️",
  "Eu adoro você. 😊🥰😻",
  "Eu lhe quero para sempre. ❤️♾️",
  "Quero que você seja minha companheira para o resto da vida. ❤️"
];

var shuffledMessages = [];
var currentIndex = 0;

// Função para embaralhar a lista de frases
function shuffleArray(array) {
  for (var i = array.length - 1; i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1));
    var temp = array[i];
    array[i] = array[j];
    array[j] = temp;
  }
  return array;
}

document.getElementById("surpriseButton").addEventListener("click", function() {
  // Embaralha a lista de frases apenas no primeiro clique
  if (shuffledMessages.length === 0) {
    shuffledMessages = shuffleArray(messages);
    currentIndex = 0;
  }

  // Mostra a próxima frase da lista embaralhada
  if (currentIndex < shuffledMessages.length) {
    document.getElementById("message").textContent = shuffledMessages[currentIndex];
    document.getElementById("myModal").style.display = "block";
    currentIndex++;
  } else {
    // Se todas as frases foram exibidas, embaralha a lista novamente
    shuffledMessages = shuffleArray(messages);
    currentIndex = 0;
    // Exibe a primeira frase da nova lista embaralhada
    document.getElementById("message").textContent = shuffledMessages[currentIndex];
    document.getElementById("myModal").style.display = "block";
    currentIndex++;
  }
});

document.getElementsByClassName("close")[0].addEventListener("click", function() {
  document.getElementById("myModal").style.display = "none";
});